language: node_js

cache:
  directories:
    - ~/.npm
    - ~/.cache

addons:
  chrome: stable # 81 at the time of writing

notifications:
  email: false

install: npm ci

jobs:
  include:
    - stage: 'test'
      node_js: lts/*
      script:
        - npm run build
        - npm run examples:build
        - npm run test:prod && npm run report-coverage
        - npm run e2e:ci

    - stage: 'deploy'
      if: type = push AND branch = master OR branch = alpha OR branch = beta
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          all_branches: true
