language: node_js

cache:
  directories:
    - ~/.npm
    - ~/.cache

addons:
  chrome: stable # 80 at the time of writing

notifications:
  email: false

install: npm ci

jobs:
  include:
    - stage: 'Test'
      node_js: lts/*
      script:
        - npm run build
        - npm run examples:build
        - npm run test:prod && npm run report-coverage
        - npm run e2e:ci

    - stage: 'Release'
      if: branch = master AND type = push
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          branch: master
